# HTTP server configuration
http:
  # server listener
  listen: "127.0.0.1:8080"

  # Proxy path in upstream
  proxy:
    /services/s3: 
      - "127.0.0.1:3007"
      - "127.0.0.1:3008"
      - "127.0.0.1:3009"
  # Authentication if need
  security:
    jwt-secret: "YWQ3NDMwM2JlZTk4MTVmZDMwZGZkYjhlNjQxNTM1YzQwNzFjNDQ4Nzk5NzQxMTA2N2U0NzVkN2I0YjkzOTgzMDUwY2Q4ODdhYTE2NjZkNWExYzM5N2EyMGI0OTIwOWYzMGNjYzc3NzNmOWFkMDQzYTJmMWQ5MjE0MGFlMDhlNWM="

# buntDB configuration
buntdb:
  path: "build/package/bunt.db"